# Generated by Django 4.2.11 on 2025-11-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the exam was started', null=True),
        ),
    ]
