# Generated by Django 4.2.11 on 2026-01-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_calendarsource_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_points_earned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_points_possible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(help_text='Question ID/order from the grading system')),
                ('order', models.IntegerField(default=0)),
                ('points_earned', models.FloatField(default=0)),
                ('points_possible', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.examsubmission')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('submission', 'question_id')},
            },
        ),
    ]
