# Generated by Django 4.2.11 on 2026-01-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_examsubmission_graded_at_examsubmission_is_graded_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiongrade',
            unique_together={('submission', 'order')},
        ),
    ]
